[build-system]
requires = ["setuptools>=65.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "shared-models"
version = "0.1.0"

[tool.setuptools]
packages = ["shared_models"]
package-dir = {shared_models = "."}